language: php
sudo: required
php:
  - 5.6
  - 7.0
install:
  - sudo mkdir -p /var/www/html/log
  - sudo chmod 777 -R /var/www/html/log
  - sudo mkdir -p /tmp/jeedom-cache
  - sudo chmod 777 -R /tmp/jeedom-cache
  - sudo apt-get update
  - sudo chmod +x install/install.sh
  - sudo install/install.sh -w /home/travis/build/jeedom/core -s 2 -m root
  - sudo install/install.sh -w /home/travis/build/jeedom/core -s 3 -m root
  - sudo install/install.sh -w /home/travis/build/jeedom/core -s 4 -m root
  - sudo install/install.sh -w /home/travis/build/jeedom/core -s 7 -m root
  - sudo install/install.sh -w /home/travis/build/jeedom/core -s 8 -m root
  - sudo php install/install.php mode=force
  - sudo chmod 777 -R /home/travis/build/jeedom
  - sudo chown www-data:www-data -R /home/travis/build/jeedom
notifications:
  slack: jeedom:uVLJjs0ANyRFWpFcUok4QFLr